# Generated by Django 3.0.4 on 2020-07-28 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField(default=0)),
                ('image', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('stock', models.CharField(choices=[('In Stock', 'In Stock'), ('Out of Stock', 'Out of Stock')], max_length=100)),
                ('brand', models.CharField(max_length=300)),
                ('Labels', models.CharField(blank=True, choices=[('Hot', 'Hot'), ('New', 'New'), ('Sale', 'Sale')], max_length=100)),
                ('special_offer', models.BooleanField(default=False)),
                ('front', models.BooleanField(default=False)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Category')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Subcategory')),
            ],
        ),
    ]
