# Generated by Django 3.0.4 on 2020-07-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('', 'default')], max_length=200),
        ),
    ]
