# Generated by Django 3.0.4 on 2020-08-01 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200728_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='Images'),
        ),
    ]
