# Generated by Django 3.0.4 on 2020-08-08 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200808_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='quantity',
        ),
    ]
