# Generated by Django 3.0.4 on 2020-08-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_wish_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hotdeal',
            field=models.BooleanField(default=False),
        ),
    ]
