# Generated by Django 3.0.4 on 2020-08-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='order_details',
            field=models.TextField(blank=True),
        ),
    ]
