# Generated by Django 3.0.4 on 2020-08-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_checkout_order_details'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
