# Generated by Django 3.0.4 on 2020-08-24 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_order_orderproducts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproducts',
            name='item',
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='slug',
            field=models.TextField(default='slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
